### ISSUE TITLE
Persistent crashing on macOS Ventura

### ISSUE THREAD

**Issue by T1T4N** [Browsers-software/browsers#8]
The app crashes on startup on macOS Ventura 13.1 (22C65) without even showing any UI.
This prevents any external link from being opened until the system default browser app is changed to something other than Browsers.

**To Reproduce**
1. Set browsers as the default browser in macOS System Settings
2. Click on any link or manually run `/Applications/Browsers.app/Contents/MacOS/Browsers`
3. See error

**Expected behavior**
A context (pop-up) menu is shown, allowing the choice of one of the installed browsers

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.1 (22C65)
 - Browsers:
   - Safari 16.2
   - Microsoft Edge 108.0.1462.76
   - Mozilla Firefox 108.0.2
 - Other apps: [iTerm 2](https://iterm2.com/)

**Additional context**
Rust backtrace:
```
❯ RUST_BACKTRACE=full /Applications/Browsers.app/Contents/MacOS/Browsers 'https://www.google.com'
2023-01-10T15:23:33.288833+01:00  INFO browsers: Starting Browsers
2023-01-10T15:23:33.288873+01:00  INFO browsers: Logging to /Users/user/Library/Logs/software.Browsers/browsers.log
2023-01-10T15:23:33.39782+01:00  INFO browsers::macos_utils: Added app: InstalledBrowser { executable_path: "/System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app/Contents/MacOS/Safari", display_name: "Safari", bundle: "com.apple.Safari", user_dir: "", icon_path: "/Users/user/Library/Caches/software.Browsers/icons/com.apple.Safari.png", profiles: [InstalledBrowserProfile { profile_cli_arg_value: "", profile_cli_container_name: None, profile_name: "", profile_icon: None }] }
2023-01-10T15:23:33.43048+01:00  INFO browsers::macos_utils: Added app: InstalledBrowser { executable_path: "/Applications/iTerm.app/Contents/MacOS/iTerm2", display_name: "iTerm2", bundle: "com.googlecode.iterm2", user_dir: "", icon_path: "/Users/user/Library/Caches/software.Browsers/icons/com.googlecode.iterm2.png", profiles: [InstalledBrowserProfile { profile_cli_arg_value: "", profile_cli_container_name: None, profile_name: "", profile_icon: None }] }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase', src/chromium_profiles_parser.rs:43:59
stack backtrace:
   0:        0x1004241ac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he84d5e26d26c914d
   1:        0x10035b394 - core::fmt::write::h07c7e4739f78f3b0
   2:        0x100401a1c - std::io::Write::write_fmt::h4a3c5f094ffc65e8
   3:        0x100427784 - std::sys_common::backtrace::print::h6fc2cc8be2392a8e
   4:        0x1004273e4 - std::panicking::default_hook::{{closure}}::h3bb44ba6ff437e23
   5:        0x1004282b8 - std::panicking::rust_panic_with_hook::h9b8acc949e1fb807
   6:        0x100427e3c - std::panicking::begin_panic_handler::{{closure}}::hfc38b2cc56e3623c
   7:        0x100427db0 - std::sys_common::backtrace::__rust_end_short_backtrace::hbafd151207fc448f
   8:        0x100427d8c - _rust_begin_unwind
   9:        0x100449100 - core::panicking::panic_fmt::h8c7f3d540a75578f
  10:        0x1004492d0 - core::result::unwrap_failed::h666d2c7e0d130ea0
  11:        0x100305334 - browsers::chromium_profiles_parser::find_chromium_profiles::h4e2a156bece19969
  12:        0x100290178 - browsers::utils::OSAppFinder::get_installed_browsers_cached::ha42eebba31973249
  13:        0x1002e8bfc - browsers::generate_all_browser_profiles::h1b6769b8818a16b2
  14:        0x1002eeadc - browsers::basically_main::h920febe78a4fccdc
  15:        0x10034b400 - browsers::main::h39fef18b4555ca41
  16:        0x10034fb68 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7f8e7c3316bd894f
  17:        0x100349bac - _main
```

**Comment by liias** [comment]
@T1T4N could you try version [0.1.0-rc23](https://github.com/Browsers-software/browsers/releases/tag/0.1.0-rc23) and see if that works for you?

**Comment by T1T4N** [comment]
@liias It fails with a different error this time:

```
❯ RUST_BACKTRACE=full /Applications/Browsers.app/Contents/MacOS/Browsers

2023-01-16T19:06:57.367669+01:00  INFO browsers: Starting Browsers
2023-01-16T19:06:57.3677+01:00  INFO browsers: Logging to /Users/robert/Library/Logs/software.Browsers/browsers.log
2023-01-16T19:06:57.372139+01:00  INFO browsers::utils: Config: /Users/robert/Library/Application Support/software.Browsers/config.json
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/ui.rs:53:42
stack backtrace:
   0:        0x1027dbe44 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he84d5e26d26c914d
   1:        0x10271302c - core::fmt::write::h07c7e4739f78f3b0
   2:        0x1027b96b4 - std::io::Write::write_fmt::h4a3c5f094ffc65e8
   3:        0x1027df41c - std::sys_common::backtrace::print::h6fc2cc8be2392a8e
   4:        0x1027df07c - std::panicking::default_hook::{{closure}}::h3bb44ba6ff437e23
   5:        0x1027dff50 - std::panicking::rust_panic_with_hook::h9b8acc949e1fb807
   6:        0x1027dfab4 - std::panicking::begin_panic_handler::{{closure}}::hfc38b2cc56e3623c
   7:        0x1027dfa48 - std::sys_common::backtrace::__rust_end_short_backtrace::hbafd151207fc448f
   8:        0x1027dfa24 - _rust_begin_unwind
   9:        0x102800c78 - core::panicking::panic_fmt::h8c7f3d540a75578f
  10:        0x102800d18 - core::panicking::panic::h2505ca165b8854d6
  11:        0x1026e0150 - browsers::ui::UI::real_to_ui_browsers::h2e34b6bbd09f6ae7
  12:        0x102693704 - browsers::basically_main::h920febe78a4fccdc
  13:        0x102703098 - browsers::main::h39fef18b4555ca41
  14:        0x102707800 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7f8e7c3316bd894f
  15:        0x102701844 - _main
```

**Comment by liias** [comment]
Oops, that should also be fixed now. Once https://github.com/Browsers-software/browsers/actions/runs/3933100171 is finished, there should be 0.1.0-rc24 at https://github.com/Browsers-software/browsers/releases

Thanks for beta testing :)

**Comment by liias** [comment]
> @liias I tested 0.1.0-rc25 and it is no longer crashing!

Glad to hear! Thanks again for reporting this. Happy using!
